<center>
<img src="./images/ods_stickers.jpg" />
    
# Introducción al Machine Learning 2020

Basado en material de Pedro Pury y  Sebastian Raschka (sraschka@wisc.edu) Traducido y editado al español por [Ana Georgina Flesia](https://www.linkedin.com/in/georginaflesia/). Este material esta sujeto a los términos y condiciones de la licencia  [Creative Commons CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/). Se permite el uso irrestricto para todo propósito no comercial.

### Ejercicio 1: Árboles de decision

Al entrar al bar, sus **cinco** amigos, quienes se reúnen al salir
de trabajar, ya tiene sus bebidas sobre la mesa.
María que tiene un cargo de gerente paga la ronda la mitad de las
veces. Pablo paga la ronda la cuarta parte de las veces, mientras
que Sara y Carlos que son becarios pagan indistintamente entre ambos
la octava parte de las veces. Juan nunca sacó la billetera desde
que se reúnen los viernes.



a)  ¿Qué fracción de las veces ud. paga la ronda?

Primero obtenemos las probabilidades de pagar de cada uno de mis amigos:

$p_{Maria} = \dfrac{1}{2}$, $p_{Sara} = \dfrac{1}{16}$, $p_{Carlos} = \dfrac{1}{16}$, $p_{Pablo} = \dfrac{1}{4}$, 
$p_{Juan} = 0$ 

Luego la probabilidad ($p_{}$) de que yo deba pagar es:

$p_{} = 1 - p_{Maria} - p_{Pablo} - p_{Sara} - p_{Carlos} -p_{Juan} = 1 - \dfrac{1}{2} - \dfrac{1}{4} - \dfrac{1}{16} - \dfrac{1}{16} - 0 = \dfrac{1}{8}$ 


b) Calcular la entropía de la distribución de probabilidad
con la que cada uno paga la ronda. ¿Cuál es el número medio
de preguntas (de respuesta binaria) que necesitan hacerse para
saber quién paga la ronda? [articulo](https://nusgrem.es/informacion-entropia-probabilidad/)


$Entropy(P) = \sum -p_{i}\log_{2}p_{i} = -\dfrac{1}{2}\log_2 \dfrac{1}{2} - \dfrac{1}{4}\log_2 \dfrac{1}{4} - \dfrac{2}{16}\log_2 \dfrac{1}{16} - 0 \log_2 0 - \dfrac{1}{8} \log_2 \dfrac{1}{8} = \dfrac{1}{2} + \dfrac{2}{4} + \dfrac{8}{16} + 0 + \dfrac{3}{8} = 1.875$

Poco después de arribar al bar se suman dos antiguos amigos quienes
no vivieron en la ciudad el último año. Ellos deciden que la próxima
ronda la debe pagar ud. y conociendo que cursa esta materia,
lo desafían a predecir que bebida tomará cada uno.




Usando la información de las tres variables binarias:
sexo, si es o no estudiante y si le gusta o no bailar,
y recordando la elección de bebidas de la noche anterior,
puede construirse la siguiente tabla:


    |Bebida | Género | Estudiante | Baile |
    --------------------------------------------
    cerveza | M      | T          | T  
    cerveza | M      | F          | T  
    vodka   | M      | F          | F  
    vodka   | M      | F          | F  
    vodka   | F      | T          | T  
    vodka   | F      | F          | F  
    vodka   | F      | T          | T 
    vodka   | F      | T          | T 
    -------------------------------------------------


c) Usando entropía de información entrenar un árbol
de decisión a partir de la tabla anterior.
Registrar todos los valores calculados para elegir las variables
en cada nodo del árbol.




Sea $S$ la colección de ejemplos de entrenamiento de la tabla. Para correr ID3 tenemos que calcular la ganancia de información ($Gain(S, A)$) para cada uno de los atributos $A$ (*Género*, *Estudiante* y *Baile*) y el que tenga la mayor ganancia.

Primero calculamos la entropía de $S$ respecto del concepto *Cerveza*. Tenemos 2 ejemplos positvos y 6 negativos, de un total de 8. Luego :

$Entropy([2+, 6-]) = -\dfrac{2}{8}\log_2 \dfrac{2}{8} - \dfrac{6}{8} \log_2 \dfrac{6}{8} = -\dfrac{1}{4}\log_2 \dfrac{1}{4} - \dfrac{3}{4} \log_2 \dfrac{3}{4} = \dfrac{1}{2} + 0.311 = 0.811$ 


Ahora podemos calcular las ganancias de información para cada atributo:

* **Género**

$|S_{M}| = 4$ y $|S_{F}| = 4$

Luego $Entropy(S_{M}) = Entropy([2+, 2-]) = 1$ y $Entropy(S_{F}) = Entropy([0+, 4-]) = 0$

$Gain(S, Genero) = 0.811 - (\dfrac{4}{8} 1 + \dfrac{4}{8} 0) = 0.311$

* **Estudiante**

$|S_{T}| = 4$ y $|S_{F}| = 4$

Luego $Entropy(S_{T}) = Entropy(S_{F}) = Entropy([1+, 3-]) = -\dfrac{1}{4} \log_2 \dfrac{1}{4} - \dfrac{3}{4} \log_2 \dfrac{3}{4} = \dfrac{1}{2} + 0.311 = 0.811$

$Gain(S, Estudiante) = 0.811 - (\dfrac{4}{8} 0.811 + \dfrac{4}{8} 0.811) = 0.811 - 0.811 = 0$

* **Baile**

$|S_{T}| = 5$ y $|S_{F}| = 3$

Luego $Entropy(S_{T}) = Entropy([2+, 3-]) = -\dfrac{2}{5} \log_2 \dfrac{2}{5} - \dfrac{3}{5} \log_2 \dfrac{3}{5} =  0.529 + 0.442 = 0.971$

Por otro lado,  $Entropy(S_{f}) = Entropy([0+, 3-]) = 0$

$Gain(S, Baile) = 0.811 - (\dfrac{5}{8} 0.971 + \dfrac{3}{8} 0) = 0.811 - 0.607 = 0.204$

Según las ganancias calculadas el atributo *Género* provee la mejor predicción del atributo *Cerveza*, por lo tanto se elige **Género** como el nodo raíz del árbol. De la raíz salen dos ramas $F$ y $M$; $F$ tiene como hoja a $Vodka$ mientras que con $M$ se tiene que agregar otro nodo porque tenemos 4 ejemplos, 2 con *Cerveza* y 2 con *Vodka*.

<br> 
Por lo tanto ahora definimos $S_{1}$ con esos 4 ejemplos y calculamos su entropía teniendo en cuenta el concepto *Cerveza*.

$Entropy(S_{1}) = Entropy([2+, 2-]) = 1$

Ahora calculamos la gananancia con respecto en los conceptos que quedan:

* **Baile**

$|S_{{1}_T}| = 2$ y $|S_{{1}_F}| = 2$

Luego $Entropy(S_{{1}_T}) = Entropy([2+, 0-]) = 0$ y $Entropy(S_{{1}_F}) = Entropy([0, 2-]) = 0$

Por lo tanto $Gain(S_{1}, Baile) = 1 - (\dfrac{2}{4} 0 + \dfrac{2}{4} 0) = 1$

* **Estudiante**

$|S_{{1}_T}| = 1$ y $|S_{{1}_F}| = 3$

Luego $Entropy(S_{{1}_T}) = Entropy([1+, 0-]) = 0$ 

También, $Entropy(S_{{1}_F}) = Entropy([1+, 2-]) = -\dfrac{1}{3} \log_2 \dfrac{1}{3} - -\dfrac{2}{3} \log_2 \dfrac{2}{3} = 0.528 + 0.39 = 0.918$

Por lo tanto $Gain(S_{1}, Estudiante) = 1 - (\dfrac{1}{4} 0 + \dfrac{3}{4} 0.918) = 1 - 0.689 = 0.311$

Así que se elige como segundo nodo **Baile** del cual saldrán dos ramas: la rama $T$ y $F$, la primera lleva a la hoja $Cerveza$ y la segunda a la hoja $Vodka$. 

El árbol que nos queda es este:

<center>
<img src="./images/decision_tree_3.png" />


d)  Proponer una poda del árbol y justificarla.

Solo podemos quitar la rama baile, si hacemos eso perdemos la clasificacion del $100 \%$ lograda y obtenemos una del $75 \%$.


## 1) Implementing an ID3 Decision Tree ( problem suggested by: Sebastian Raschka (sraschka@wisc.edu)  )

### 1.1) Splitting a node 


First, we are going to implement a function that splits a dataset along a feature axis into sub-datasets. Since we are going to implement a decision tree that only supports categorical features (like ID3) for simplicity, you do not need to account for continuous feature variables. In other words, the splitting function only needs to support integer NumPy arrays.  

To provide an intuitive example, suppose you are given the following NumPy array with four feature values, feature values 0-3:

    np.array([0, 1, 2, 1, 0, 3, 1, 0, 1, 2])
    
The function you are going to implement should return a dictionary, where each dictionary key represents a unique value in the array, and the values are the indices in that array that map to the respective feature value. Hence, based on the feature array above, your `split` function should return the following dictionary:

    {0: array([0, 4, 7]), 
     1: array([1, 3, 6, 8]), 
     2: array([2, 9]), 
     3: array([5])}

Tip: I recommend you to use `np.where` and `np.unique` functions to make the implementation easier. If you do not remember these functions from the "computational foundations" lectures, you can either look up those functions in the NumPy documentation online, or you can execute `np.where?` and `np.unique?` in a new code cell to get more information.

In [2]:
import numpy as np

In [64]:
def split(array):
    
    split_array = {}
    unique = np.unique(array)
    
    for u in unique:
        split_array[u] = np.where(array==u)[0]
    
    return split_array

I added the following code cell for your convenience to double-check your solution. If your results don't match the results shown below, there is a bug in your implementation.

In [65]:
# DO NOT EDIT OR DELETE THIS CELL

print(split(np.array([0, 1, 2])))
print(split(np.array([1, 0, 1, 0, 0, 1, 0])))
print(split(np.array([1, 0, 3, 2, 0, 1, 1])))

#{0: array([0]), 1: array([1]), 2: array([2])}
#{0: array([1, 3, 4, 6]), 1: array([0, 2, 5])}
#{0: array([1, 4]), 1: array([0, 5, 6]), 2: array([3]), 3: array([2])}

{0: array([0]), 1: array([1]), 2: array([2])}
{0: array([1, 3, 4, 6]), 1: array([0, 2, 5])}
{0: array([1, 4]), 1: array([0, 5, 6]), 2: array([3]), 3: array([2])}


###  1.2) Implement Entropy

After implementing the splitting function, we are now have to implement a criterion function so that we can compare splits on different features, to decide which feature is the best feature to split for growing the decision tree. As discussed in class, our splitting criterion will be Information Gain. However, before we implement an Information Gain function, we need to implement a function that computes the entropy at each node, which we need to compute Information Gain.

For your reference, we defined entropy (i.e., Shannon Entropy) as follows:

$$H(p) = \sum_i p_i \log_2 (1/p_i) = - \sum_i p_i \log_2 (p_i)$$

where you can think of $p_i$ as the proportion of examples with class label $i$ at a given node.

In [80]:
def entropy(array):
    n, entropy = len(array), 0
    
    split_array = split(array)
    
    for key in split_array.keys():
        p_i = len(split_array[key])/n
        entropy -= p_i*np.log2(p_i)
    
    return entropy

I added the following code cell for your convenience to double-check your solution. If your results don't match the results shown below, there is a bug in your implementation of the `entropy` function.

In [81]:
# DO NOT EDIT OR DELETE THIS CELL

print(round(entropy(np.array([0, 1, 0, 1, 1, 0])), 4))
print(round(entropy(np.array([1, 2])), 4))
print(round(entropy(np.array([1, 1])), 4))
print(round(entropy(np.array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])), 4))
print(round(entropy(np.array([0, 0, 0])), 4))
print(round(entropy(np.array([1, 1, 1, 0, 1, 4, 4, 2, 1])), 4))

#1.0
#1.0
#0.0
#0.4395
#0.0
#1.6577

1.0
1.0
0.0
0.4395
0.0
1.6577


### 1.3) Implement Information Gain

Now that you have a working solution for the `entropy` function, the next step is to compute the Information Gain. For your reference, information gain is computed as

$$GAIN(\mathcal{D}, x_j) = H(\mathcal{D}) - \sum_{v \in Values(x_j)} \frac{|\mathcal{D}_v|}{|\mathcal{D}|} H(\mathcal{D}_v).$$

In [100]:
def information_gain(x_array, y_array):
    parent_entropy = entropy(x_array)

    split_dict = split(y_array)
    
    d = len(x_array) 
    for val in split_dict:
        freq = len(split_dict[val])/d
        child_entropy = entropy(x_array[split_dict[val]])
        parent_entropy -= freq*child_entropy
        
    return parent_entropy

I added the following code cell for your convenience to double-check your solution. If your results don't match the results shown below, there is a bug in your implementation of the `information_gain` function.

In [102]:
# DO NOT EDIT OR DELETE THIS CELL

x = np.array([0, 1, 0, 1, 0, 1])
y = np.array([0, 1, 0, 1, 1, 1])
print(round(information_gain(x, y), 4))

x = np.array([0, 0, 1, 1, 2, 2])
y = np.array([0, 1, 0, 1, 1, 1])
print(round(information_gain(x, y), 4))

#0.4591
#0.2516

0.4591
0.2516


### 1.4) Decision Tree Splitting

Now, we should have all the main components that we need for implementing the ID3 decision tree algorithm: a `split` function, an `entropy` function, and an `information_gain` function based on the `entropy` function. 

The next task is combine these functions to recursively split a dataset on its different features to construct a decision tree that separate the examples from different classes well. We will call this function `make_tree`. 

For simplicity, the decision tree returned by the `make_tree` function will be represented by a Python dictionary. To illustrate this, consider the following dataset:

```
Inputs:
 [[0 0]
 [0 1]
 [1 0]
 [1 1]
 [2 0]
 [2 1]]

Labels:
 [0 1 0 1 1 1]
```
 
This is a dataset with 6 training examples and two features.  The decision tree in form of the Python dictionary should look like as follows:



You should return a dictionary with the following form:

```
{'X_1 = 0': {'X_0 = 0': array([0]),
             'X_0 = 1': array([0]),
             'X_0 = 2': array([1])},
 'X_1 = 1': array([1, 1, 1])}
 ```
 
Let me further illustrate what the different parts of the dictionary mean. Here, the `'X_1'` in `'X_1 = 0'` refers feature 2 (the first column of the NumPy array; remember that Python starts the index at 0, in contrast to R). 

- 'X_1 = 0': For training examples stored in this node, the second feature has the value 0
- 'X_1 = 1': For training examples stored in this node, the second feature has the value 1

The "array" is a NumPy array that stores the class labels of the training examples at that node. In the case of `'X_1 = 0'` we actually store actually a sub-dictionary, because this node can be split further. If you have trouble understanding this dictionary representation, the following illustration might help:


![](tree-viz-1.png)

In [162]:
def make_tree(X, y):
    
    # Return array if node is empty or pure (1 example in leaf node)
    if y.shape[0] == 1 or y.shape[0] == 0:
        return y

    # Compute information gain for each feature
    gains = np.apply_along_axis(information_gain, 0, X, y)

    # Early stopping if there is no information gain
    if (gains <= 1e-05).all():
        return y
    
    # Else, get best feature
    best_feature = np.argmax(gains)

    
    results = {}
    
    # Use the `split` function to split on the best feature
    subset_dict = split(X[:, best_feature])

    # Note that each entry in the dictionary returned by 
    # split is an attribute_value:array_indices pair.
    # here, we are going to iterate over these key-value
    # pairs and select the respective examples for the
    # new child nodes
    
    for feature_value, train_example_indices in subset_dict.items():
        child_y_subset = y[train_example_indices]
        child_x_subset = np.delete(X, best_feature, 1)[train_example_indices]

        # Next, we are using "recursion," that is, calling the same
        # tree_split function on the child subset(s)
        
        results["X_%d = %d" % (best_feature, feature_value)] = \
                make_tree(child_x_subset, child_y_subset)

        
    return results

I added the following code cell for your convenience to double-check your solution. If your results don't match the results shown below, there is a bug in your implementation of the `make_tree` function.

In [163]:
# DO NOT EDIT OR DELETE THIS CELL

x1 = np.array([0, 0, 1, 1, 2, 2])
x2 = np.array([0, 1, 0, 1, 0, 1])
X = np.array([x1, x2]).T
y = np.array([0, 1, 0, 1, 1, 1])

print('Inputs:\n', X)
print('\nLabels:\n', y)

print('\nDecision tree:\n', make_tree(X, y))

#Inputs:
# [[0 0]
# [0 1]
# [1 0]
# [1 1]
# [2 0]
# [2 1]]

#Labels:
# [0 1 0 1 1 1]

#Decision tree:
# {'X_1 = 0': {'X_0 = 0': array([0]), 'X_0 = 1': array([0]), 'X_0 = 2': array([1])}, 'X_1 = 1': array([1, 1, 1])}


Inputs:
 [[0 0]
 [0 1]
 [1 0]
 [1 1]
 [2 0]
 [2 1]]

Labels:
 [0 1 0 1 1 1]

Decision tree:
 {'X_1 = 0': {'X_0 = 0': array([0]), 'X_0 = 1': array([0]), 'X_0 = 2': array([1])}, 'X_1 = 1': array([1, 1, 1])}


### 1.5) Building a Decision Tree API

The final step of this part of the homework is now to write an API around our decision tree code so that we can use is for making predictions. Here, we will use the common convention, established by scikit-learn, to implement the decision tree as a Python class with 

- a `fit` method that learns the decision tree model from a training set via the `make_tree` function we already implemented;
- a `predict` method to predict the class labels of training examples or any unseen data points.

For making predictions, since not all leaf nodes are guaranteed to be single training examples, we will use a majority voting function to predict the class label as discussed in class. I already implemented a `_traverse` method, which will recursively traverse a decision tree dictionary that is produced by the `make_tree` function.

Note that for simplicity, the `predict` method will only be able to accept one data point at a time (instead of a collection of data points). Hence `x` is a vector of size $\mathbb{R}^m$, where $m$ is the number of features. I use capital letters `X` to denote a matrix of size $\mathbb{R}^{n\times m}$, where $n$ is the number of training examples.

In [166]:
class ID3DecisionTreeClassifer(object):
    
    def __init__(self):
        pass
    
    def fit(self, X, y):
        self.splits_ = make_tree(X, y)
        
    def _majority_vote(self, label_array):
        values,counts = np.unique(label_array,return_counts=True)
        ind = np.argmax(counts)
        return label_array[ind]
        
    def _traverse(self, x, d):
        if isinstance(d, np.ndarray):
            return d
        for key in d:
            name, value = key.split(' = ')
            feature_idx = int(name.split('_')[-1])
            value = int(value)
            if x[feature_idx] == value:
                return self._traverse(x, d[key])
        
    def predict(self, x):
        
        label_array = self._traverse(x, self.splits_)
        return self._majority_vote(label_array)

I added the following code cell for your convenience to double-check your solution. If your results don't match the results shown below, there is a bug in your implementation of the `make_tree` function.

In [167]:
# DO NOT EDIT OR DELETE THIS CELL

tree = ID3DecisionTreeClassifer()
tree.fit(X, y)

print(tree.predict(np.array([0, 0])))
print(tree.predict(np.array([0, 1])))
print(tree.predict(np.array([1, 0])))
print(tree.predict(np.array([1, 0])))
print(tree.predict(np.array([1, 1])))
print(tree.predict(np.array([2, 0])))
print(tree.predict(np.array([2, 1])))

#0
#1
#0
#0
#1
#1
#1

0
1
0
0
1
1
1
